traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true

metricsGenerator:
  enabled: true
  config:
    storage:
      remote_write:
        - url: http://mimir-gateway.mimir.svc/prometheus/api/v1/write
    processor:
      service_graphs:
        dimensions: []
      span_metrics:
        dimensions: []

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics

storage:
  trace:
    backend: local

gateway:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: tempo-gateway.k8s.orb.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
